### ISSUE TITLE
SSL on Google Cloud instance

### ISSUE THREAD

**Issue by vervaekejonathan** [pylast/pylast#201]
Using pylast on Google Cloud (Python 2.7) returns an error:

```python
AttributeError: 'module' object has no attribute 'create_default_context'
at <module> (/base/data/home/apps/xxx/lib/pylast/__init__.py:204)
```

Currently 'patched' this by disabling ssl connection in `def _can_use_ssl_securely:`

**Comment by hugovk** [comment]
What's the full x.y.z Python version number?

**Comment by vervaekejonathan** [comment]
Not working on 2.7.9
Can confirm it does work on 2.7.13

**Comment by hugovk** [comment]
That's odd, [docs](https://docs.python.org/2/library/ssl.html#ssl.create_default_context) says `create_default_context` was new in 2.7.9.

@simmel Any ideas here?

**Comment by simmel** [comment]
Either the docs are wrong or Google has broken their Python 2.7.9. Both sound weird = /

@vervaekejonathan I have no experience with Googles Cloud services so just to clarify before I dive into this:
* Is this on App, Compute or Container Engine?
* Do you know of a way to create support tickets with Google Cloud?
* Do you have or can provide a minimal working example?

**Comment by hugovk** [comment]
Closing due to lack of response.

**Comment by sampsyo** [comment]
Hi! We're having a similar problem on Travis-CI, which currently uses Python 2.7.6. You can see the error here:
https://travis-ci.org/beetbox/beets/jobs/294664392#L1109

Is this call (and commensurate incompatibility with old versions of Python 2.7) necessary?

**Comment by hugovk** [comment]
It's from https://github.com/pylast/pylast/pull/178 to only use HTTPS, Last.fm authentication will be HTTPS-only in the near future, and they say all API calls should be via HTTPS too.

Python 2.7.6 was [released in 2013](https://www.python.org/download/releases/2.7.6/) so is pretty old.

I see the `python: 2.7.13` build is now passing (I wonder if they have `2.7.14` too), which is good, but `2.7_with_system_site_packages` is stuck on 2.7.6.


A couple of options:

* #178 was released in pylast 1.7.0, so you can pin to the previous version:
  `pip install pylast < 1.7.0`
  Or only do that for old Python 2.7.

* Use a newer version of Python 2.7. Can you use a standard 2.7 image instead of `2.7_with_system_site_packages`? Looks like you can: https://github.com/beetbox/beets/pull/2722 :)

**Comment by sampsyo** [comment]
Amazing! Thank you for diagnosing that. And, more broadly, for maintaining pylast—it's great to see that it's still making progress.

**Comment by hugovk** [comment]
You're welcome!
